---
title: "TP3"
format: html
---

```{r}
donnees <- read.csv("Donnees_qualite_vins.csv", sep = ",")
summary(donnees)
```

```{r}
cor(donnees)
#les quaracteristiques qui influencent le plus la qualité du vin sont l'alcohol, le volatile.acidity et les sulphates
```

```{r}
library(class)
library(dplyr)
library(caTools)
set.seed(2026)

split = sample.split(donnees$quality, 
                     SplitRatio = 0.75)
train = subset(donnees, 
                      split == TRUE)
test = subset(donnees, 
                  split == FALSE)
```

```{r}
library(ranger)

```

```{r}
library(rpart)
library(rsample)

# Grow a (nearly) full classification tree
set.seed(123)
full_tree <- rpart(quality ~ ., data = train, method = "class")

# The decision rules, as text
full_tree
```
# alcohol = 11.5, pH = 2, free.sulfur.dioxide = 7.6, sulphates = 0.42, volatile.acidity = 0.98 -> NON

```{r}
cor(train)
```

```{r}
library(caret)
library(randomForest)
library(ggplot2)
library(dplyr)
set.seed(222)
ind <- sample(2, nrow(donnees), replace = TRUE, prob = c(0.7, 0.3))
train <- donnees[ind==1,]
test <- donnees[ind==2,]
rf <- randomForest(quality~., data=train, proximity=TRUE)
print(rf)
```